spring:
  cloud:
    gateway:
      routes:
        - uri: https://albertoimpl.com
          predicates:
            - Path=/wasm
          filters:
            - StripPrefix=1
            - CustomSumWASMFilter
server:
  port: 8081